### PR TITLE
fix this issue https://github.com/ayeo-flex-org/pulsar-flex/issues/90…

### PR DESCRIPTION
**Pull request by geoffhendrey**
…. Closes underlying socket and dangling timeout

### CODE REVIEW

**Comment by geoffhendrey** [comment]
is this a problem with the test suite? The tests ran fine on my local machine. It appears docker-compose isn't found in CI? I see the following error at the start of the CI tests.

```
Creating pulsar via docker-compose from path /home/runner/work/pulsar-flex/pulsar-flex/scripts/docker/pulsar-jwt/2.8.0/docker-compose.yml
Waiting 60000ms for pulsar-standalone to start before creating configurations
docker-compose killed Error: Command failed: docker-compose -f /home/runner/work/pulsar-flex/pulsar-flex/scripts/docker/pulsar-jwt/2.8.0/docker-compose.yml up --build
/bin/sh: 1: docker-compose: not found

Validating pulsar is up still up after waiting
(node:[17](https://github.com/ayeo-flex-org/pulsar-flex/actions/runs/11614750705/job/32349230459#step:5:18)84) UnhandledPromiseRejectionWarning: Error: pulsar-standalone-pulsar-flexhas been closed, tests setup aborted - maybe try to increase wait standaloneWaitTime
    at /home/runner/work/pulsar-flex/pulsar-flex/scripts/test-setup.js:52:11
   ```

**Comment by danielsinai** [comment]
Hi @geoffhendrey 
Getting back to you, it seems like your PR is not relevant to the problems and something in the CI broke.

If you don't mind I will fix it sometime this weekend/next week and then I will ask you to pull this changes so the CI will pass

**Comment by geoffhendrey** [comment]
@danielsinai thank you very much!

**Comment by danielsinai** [comment]
No problem @geoffhendrey 
Just fixed the issue #92 with the CI feel free to pull from main, rerun your tests and I will approve the PR 👍

**Comment by geoffhendrey** [comment]
@danielsinai merged main into my branch, all tests pass locally. You may need to approve the workflow to run the tests for this PR.

**Review by danielsinai — APPROVED** [review]

**Comment by geoffhendrey** [comment]
@danielsinai I do not have permissions to merge. Can you merge this PR?

**Comment by danielsinai** [comment]
Done @geoffhendrey thx for your contribution!

**Pull request merged**
